version: '3.7'

# Settings and configurations that are common for all MinIO containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2021-12-20T22-07-16Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# MinIO Storage Volumes
volumes:
  s3data1-1:
  s3data1-2:
  s3data2-1:
  s3data2-2:
  s3data3-1:
  s3data3-2:
  s3data4-1:
  s3data4-2:

networks:
  application:
    driver: bridge

services:

  # nginx / Reverse Proxy Section
  
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

  # MinIO Servers / Object Storage Section

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - s3data1-1:/data1
      - s3data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - s3data2-1:/data1
      - s3data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - s3data3-1:/data1
      - s3data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - s3data4-1:/data1
      - s3data4-2:/data2