version: '3.7'

networks:
  application:
    driver: bridge

volumes:
  kafka_data:
    driver: local

services:
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_CFG_ADVERTISED_LISTENERS: ${KAFKA_CFG_ADVERTISED_LISTENERS}
      KAFKA_CFG_ZOOKEEPER_CONNECT: ${KAFKA_CFG_ZOOKEEPER_CONNECT}
      ALLOW_PLAINTEXT_LISTENER: ${KAFKA_ALLOW_PLAINTEXT_LISTENER}
    ports:
      - '9092:9092'
    networks:
      - application
    depends_on:
      - zookeeper

      
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: ${ZOOKP_ALLOW_ANONYMOUS_LOGIN}
    networks:
      - application